FROM golang:1.22-bookworm AS builder
WORKDIR /app
COPY . .

# Build the op-deployer binary
RUN CGO_ENABLED=0 go build -o /op-deployer ./op-deployer/cmd/op-deployer

FROM debian:bookworm-20240812-slim

# Install ca-certificates so that HTTPS requests work
RUN apt-get update && apt-get install -y ca-certificates

COPY --from=builder /op-deployer /op-deployer
RUN ln -s /op-deployer /usr/local/bin/op-deployer

ENTRYPOINT ["/op-deployer"]
