# Espresso OP Integration Docker Setup

services:
  l1:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 3s
      timeout: 2s
      retries: 40
    build:
      context: ./ops/docker/deployment-utils
    image: l1-geth:espresso
    command:
      - geth
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,net,web3,personal,miner,admin
      - --http.port=8545
      - --nodiscover
      - --dev
      - --miner.etherbase=0x0000000000000000000000000000000000000000
    ports:
      - "8545:8545" # L1 RPC
    networks:
      - opnet

  op-node-sequencer:
    build:
      context: .
      dockerfile: ./ops/docker/op-stack-go/Dockerfile
      target: op-node-target
    image: op-node-sequencer:espresso
    depends_on:
      l1:
        condition: service_healthy
    environment:
      L1_RPC: http://l1:8545
    volumes:
      - ./config:/config
    command:
      - op-node
      - --l1=http://l1:8545
      - --l2=http://op-geth:8551
      - --l2.jwt-secret=/config/jwt.txt
      - --rollup.config=/config/op-node/rollup_devnet.json
      - --sequencer.enabled=true
    networks:
      - opnet

  op-node-verifier:
    build:
      context: .
      dockerfile: ./ops/docker/op-stack-go/Dockerfile
      target: op-node-target
    image: op-node-verifier:espresso
    depends_on:
      l1:
        condition: service_healthy
    environment:
      L1_RPC: http://l1:8545
    volumes:
      - ./config:/config
    command:
      - op-node
      - --l1=http://l1:8545
      - --l2=http://op-geth:8551
      - --l2.jwt-secret=/config/jwt.txt
      - --rollup.config=/config/op-node/rollup_devnet.json
    networks:
      - opnet

  caff-node:
    build:
      context: .
      dockerfile: ./ops/docker/op-stack-go/Dockerfile
      target: op-node-target
    image: caff-node:espresso
    depends_on:
      l1:
        condition: service_healthy
    environment:
      L1_RPC: http://l1:8545
    volumes:
      - ./config:/config
    command:
      - op-node
      - --l1=http://l1:8545
      - --l2=http://op-geth:8551
      - --l2.jwt-secret=/config/jwt.txt
      - --rollup.config=/config/op-node/rollup_devnet.json
      - --caff.node=true
    networks:
      - opnet

  op-batcher:
    build:
      context: .
      dockerfile: ./ops/docker/op-stack-go/Dockerfile
      target: op-batcher-target
    image: op-batcher:espresso
    depends_on:
      - op-node-sequencer
    environment:
      L1_RPC: http://l1:8545
    volumes:
      - ./packages/contracts-bedrock/lib/superchain-registry/ops/testdata/monorepo:/config
    command:
      - op-batcher
      - --l1-eth-rpc=http://l1:8545
      - --l2-eth-rpc=http://op-geth:8551
      - --rollup-rpc=http://op-node-sequencer:8545
      - --espresso-url=http://espresso-dev-node:24000
      - --espresso-light-client-addr=0x703848f4c85f18e3acd8196c8ec91eb0b7bd0797
    networks:
      - opnet

  op-proposer:
    build:
      context: .
      dockerfile: ./ops/docker/op-stack-go/Dockerfile
      target: op-proposer-target
    image: op-proposer:espresso
    depends_on:
      - op-node-sequencer
    volumes:
      - ./packages/contracts-bedrock/lib/superchain-registry/ops/testdata/monorepo:/config
    command:
      - op-proposer
      - --l1-eth-rpc=http://l1:8545
      - --rollup-rpc=http://op-node-sequencer:8545
      - --game-factory-address=0xDC9a4dba410aaC9D98a848710Aa82601752DBd44
      - --proposal-interval=10m
    networks:
      - opnet

  op-deployer:
    build:
      context: .
      dockerfile: ./op-deployer/Dockerfile.default
    image: op-deployer:espresso
    depends_on:
      - l1
    volumes:
      - ./packages/contracts-bedrock/lib/superchain-registry/ops/testdata/monorepo:/config
    restart: "no"
    networks:
      - opnet

  espresso-dev-node:
    image: ghcr.io/espressosystems/espresso-sequencer/espresso-dev-node:release-goldendoodle
    ports:
      - "24000:24000" # Espresso sequencer
      - "24002:24002" # Espresso dev node
      - "31003:31003" # Espresso builder
    volumes:
      - espresso-data:/data
    networks:
      - opnet
    environment:
      RUST_LOG: info
      ESPRESSO_SEQUENCER_STORAGE_PATH: /data/espresso

networks:
  opnet:

volumes:
  espresso-data:
