################################################################
#                   PROFILE: DEFAULT (local)                   #
################################################################

[profile.default]

src = 'src'
out = 'forge-artifacts'
script = 'scripts'
build_info_path = 'artifacts/build-info'
snapshots = 'notarealpath'               # workaround for foundry#9477
allow_internal_expect_revert = true      # workaround described in https://github.com/PaulRBerg/prb-math/issues/248

use_literal_content = true

optimizer = true
optimizer_runs = 999999

additional_compiler_profiles = [
  { name = "dispute", optimizer_runs = 5000 },
  { name = "via-ir", via_ir = true },
]
compilation_restrictions = [
  { paths = "src/dispute/FaultDisputeGame.sol", optimizer_runs = 5000 },
  { paths = "src/dispute/v2/FaultDisputeGameV2.sol", optimizer_runs = 5000 },
  { paths = "src/dispute/PermissionedDisputeGame.sol", optimizer_runs = 5000 },
  { paths = "src/dispute/v2/PermissionedDisputeGameV2.sol", optimizer_runs = 5000 },
  { paths = "src/dispute/SuperFaultDisputeGame.sol", optimizer_runs = 5000 },
  { paths = "src/dispute/SuperPermissionedDisputeGame.sol", optimizer_runs = 5000 },
  { paths = "src/L1/OPContractsManager.sol", optimizer_runs = 5000 },
  { paths = "src/L1/OPContractsManagerStandardValidator.sol", optimizer_runs = 5000 },
  { paths = "src/L1/opcm/OPContractsManagerV2.sol", optimizer_runs = 5000 },
  { paths = "src/L1/opcm/OPContractsManagerContainer.sol", optimizer_runs = 5000 },
  { paths = "src/L1/opcm/OPContractsManagerMigrator.sol", optimizer_runs = 5000 },
  { paths = "src/L1/opcm/OPContractsManagerUtils.sol", optimizer_runs = 5000 },
  { paths = "src/L1/opcm/OPContractsManagerUtilsCaller.sol", optimizer_runs = 5000 },
  { paths = "src/L1/OptimismPortal2.sol", optimizer_runs = 5000 },
  { paths = "src/L1/ProtocolVersions.sol", optimizer_runs = 5000 },
  { paths = "src/L1/StandardValidator.sol", optimizer_runs = 5000 },
  { paths = "src/universal/StorageSetter.sol", optimizer_runs = 5000 }
]
