services:
  op-geth:
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${OP_HTTP_PORT}" ]
      interval: 3s
      timeout: 2s
      retries: 40
    image: op-geth:espresso
    depends_on:
      l2-genesis:
        condition: service_completed_successfully
      l1-geth:
        condition: service_healthy
    volumes:
      - ./deployment/l2-config:/config:ro
    environment:
      L1_RPC: http://l1-geth:${L1_HTTP_PORT:?err}
      OP_HTTP_PORT: ${OP_HTTP_PORT:?err}
      OP_ENGINE_PORT: ${OP_ENGINE_PORT:?err}
