# Espresso OP Integration Docker Setup

services:
  l1-genesis:
    restart: on-failure
    build:
      context: ../
      dockerfile: espresso/docker/l1-geth/Dockerfile
    image: l1-geth:espresso
    environment:
      - MODE=genesis
    volumes:
      - ./deployment/l1-config:/config
      - ./docker/l1-geth:/templates:ro
      - l1-data:/data

  l1-validator:
    image: sigp/lighthouse
    depends_on:
      l1-genesis:
        condition: service_completed_successfully
      l1-geth:
        condition: service_started
      l1-beacon:
        condition: service_started
    volumes:
      - l1-data:/data
      - ./deployment/l1-config:/config:ro
    command:
      - lighthouse
      - validator_client
      - --testnet-dir
      - /config
      - --beacon-nodes
      - http://l1-beacon:${L1_BEACON_PORT}
      - --init-slashing-protection
      - --datadir
      - /data/lighthouse-validator
      - --suggested-fee-recipient
      - ${OPERATOR_ADDRESS}

  l1-beacon:
    image: sigp/lighthouse
    depends_on:
      l1-genesis:
        condition: service_completed_successfully
      l1-geth:
        condition: service_started
    volumes:
      - l1-data:/data
      - ./deployment/l1-config:/config:ro
    command:
      - lighthouse
      - --datadir
      - /data/lighthouse-beacon
      - beacon_node
      - --testnet-dir
      - /config
      - --execution-endpoint
      - http://l1-geth:${L1_ENGINE_PORT}
      - --execution-jwt
      - /config/jwt.txt
      - --http
      - --http-address
      - 0.0.0.0
      - --http-port
      - ${L1_BEACON_PORT}
      - --http-allow-origin
      - "*"
      - --allow-insecure-genesis-sync
      - --target-peers
      - "0"
      - --disable-deposit-contract-sync
      - --disable-upnp
    ports:
      - "${L1_BEACON_PORT}:${L1_BEACON_PORT}"

  l1-geth:
    depends_on:
      l1-genesis:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${L1_HTTP_PORT}" ]
      interval: 3s
      timeout: 2s
      retries: 40
    build:
      context: ../
      dockerfile: espresso/docker/l1-geth/Dockerfile
    image: l1-geth:espresso
    environment:
      L1_HTTP_PORT: ${L1_HTTP_PORT:-8545}
      L1_ENGINE_PORT: ${L1_ENGINE_PORT:-8551}
      L1_CHAIN_ID: ${L1_CHAIN_ID:?err}
    volumes:
      - ./deployment/l1-config:/config:ro
      - l1-data:/data
    ports:
      - "${L1_HTTP_PORT}:${L1_HTTP_PORT}" # L1 RPC
      - "${L1_ENGINE_PORT}:${L1_ENGINE_PORT}" # L1 Engine

  l2-rollup:
    restart: on-failure
    build:
      context: ../
      dockerfile: espresso/docker/op-geth/Dockerfile
    image: op-geth:espresso
    environment:
      - MODE=rollup
      - L1_RPC=http://l1-geth:${L1_HTTP_PORT:?err}
      - OP_RPC=http://op-geth-sequencer:${OP_HTTP_PORT:?err}
    depends_on:
      l1-geth:
        condition: service_healthy
      l1-genesis:
        condition: service_completed_successfully
      op-geth-sequencer:
        condition: service_healthy
    volumes:
      - ./deployment/l2-config:/config
      - ./deployment/deployer:/deployer:ro

  l2-genesis:
    restart: on-failure
    build:
      context: ../
      dockerfile: espresso/docker/op-geth/Dockerfile
    image: op-geth:espresso
    environment:
      - MODE=genesis
      - L1_RPC=http://l1-geth:${L1_HTTP_PORT:?err}
    depends_on:
      l1-geth:
        condition: service_healthy
    volumes:
      - ./deployment/l2-config:/config
      - ./deployment/deployer:/deployer:ro

  op-geth-sequencer:
    extends:
      file: docker-compose-op-geth.yml
      service: op-geth
    volumes:
      - op-data-seq:/data
    ports:
      - "${OP_HTTP_PORT}:${OP_HTTP_PORT}"
      - "${OP_ENGINE_PORT}:${OP_ENGINE_PORT}"

  op-geth-verifier:
    extends:
      file: docker-compose-op-geth.yml
      service: op-geth
    volumes:
      - op-data-verifier:/data
    ports:
      - "8547:${OP_HTTP_PORT}"
      - "8553:${OP_ENGINE_PORT}"

  op-geth-caff-node:
    extends:
      file: docker-compose-op-geth.yml
      service: op-geth
    volumes:
      - op-data-caff-node:/data
    ports:
      - "8548:${OP_HTTP_PORT}"
      - "8554:${OP_ENGINE_PORT}"

  op-node-sequencer:
    build:
      context: ../
      dockerfile: espresso/docker/op-stack/Dockerfile
      target: op-node-target
    image: op-node-sequencer:espresso
    depends_on:
      l2-rollup:
        condition: service_completed_successfully
      op-geth-sequencer:
        condition: service_healthy
      l1-validator:
        condition: service_started
    environment:
      OP_NODE_L1_ETH_RPC: http://l1-geth:${L1_HTTP_PORT}
      OP_NODE_L1_BEACON: http://l1-beacon:${L1_BEACON_PORT}
      OP_NODE_L2_ENGINE_RPC: http://op-geth-sequencer:${OP_ENGINE_PORT}
      OP_NODE_RPC_PORT: ${ROLLUP_PORT}
    ports:
      - "${ROLLUP_PORT}:${ROLLUP_PORT}"
    volumes:
      - ./deployment/l2-config:/config:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - op-node
      - --l2.jwt-secret=/config/jwt.txt
      - --rollup.config=/config/rollup.json
      - --sequencer.enabled=true
      - --sequencer.use-finalized=true
      - --rpc.addr=0.0.0.0
      - --l1.http-poll-interval=1s
      - --l1.epoch-poll-interval=1s
      - --p2p.disable=true

  op-node-verifier:
    build:
      context: ../
      dockerfile: espresso/docker/op-stack/Dockerfile
      target: op-node-target
    image: op-node-verifier:espresso
    depends_on:
      l2-rollup:
        condition: service_completed_successfully
      op-geth-verifier:
        condition: service_started
      l1-validator:
        condition: service_started
    environment:
      L1_RPC: http://l1-geth:${L1_HTTP_PORT}
      OP_NODE_L1_ETH_RPC: http://l1-geth:${L1_HTTP_PORT}
      OP_NODE_L1_BEACON: http://l1-beacon:${L1_BEACON_PORT}
      OP_NODE_L2_ENGINE_RPC: http://op-geth-verifier:${OP_ENGINE_PORT}
      OP_NODE_RPC_PORT: ${VERIFIER_PORT}
    ports:
      - "${VERIFIER_PORT}:${VERIFIER_PORT}"
    volumes:
      - ./deployment/l2-config:/config:ro
    command:
      - op-node
      - --l2.jwt-secret=/config/jwt.txt
      - --rollup.config=/config/rollup.json
      - --rpc.addr=0.0.0.0
      - --l1.http-poll-interval=1s
      - --l1.epoch-poll-interval=1s
      - --p2p.disable=true

  caff-node:
    build:
      context: ../
      dockerfile: espresso/docker/op-stack/Dockerfile
      target: op-node-target
    image: caff-node:espresso
    depends_on:
      op-geth-caff-node:
        condition: service_started
      espresso-dev-node:
        condition: service_started
      l2-rollup:
        condition: service_completed_successfully
    environment:
      OP_NODE_L1_ETH_RPC: http://l1-geth:${L1_HTTP_PORT}
      OP_NODE_L1_BEACON: http://l1-beacon:${L1_BEACON_PORT}
      OP_NODE_L2_ENGINE_RPC: http://op-geth-caff-node:${OP_ENGINE_PORT}
      OP_NODE_CAFF_L1_ETH_RPC: http://l1-geth:${L1_HTTP_PORT}
      OP_NODE_CAFF_ESPRESSO_LIGHT_CLIENT_ADDR: "0x703848f4c85f18e3acd8196c8ec91eb0b7bd0797"
      OP_NODE_CAFF_HOTSHOT_URLS: http://espresso-dev-node:${ESPRESSO_SEQUENCER_API_PORT},http://espresso-dev-node:${ESPRESSO_SEQUENCER_API_PORT}
      OP_NODE_RPC_PORT: ${CAFF_PORT}
    ports:
      - "${CAFF_PORT}:${CAFF_PORT}"
    volumes:
      - ./deployment/l2-config:/config:ro
    command:
      - op-node
      - --l2.jwt-secret=/config/jwt.txt
      - --rollup.config=/config/rollup.json
      - --rpc.addr=0.0.0.0
      - --sequencer.enabled=false
      - --caff.node=true
      - --verifier.l1-confs=0
      - --rollup.load-protocol-versions=false
      - --rollup.halt=none
      - --l1.trustrpc=true
      - --rpc.enable-admin=true
      - --caff.next-hotshot-block-num=1
      - --caff.polling-hotshot-polling-interval=500ms
      - --log.level=debug
      - --p2p.disable=true
      - --l1.http-poll-interval=1s
      - --l1.epoch-poll-interval=1s
    restart: "no"

  op-batcher:
    profiles: ["default"]
    build:
      context: ../
      dockerfile: espresso/docker/op-stack/Dockerfile
      target: op-batcher-target
    image: op-batcher:espresso
    # It is not necessary to specify all dependencies, but a good practice.
    depends_on:
      l1-geth:
        condition: service_healthy
      op-geth-sequencer:
        condition: service_started
      op-node-sequencer:
        condition: service_started
      espresso-dev-node:
        condition: service_started
      l2-genesis:
        condition: service_completed_successfully
    environment:
      L1_RPC: http://l1-geth:${L1_HTTP_PORT}
      OP_BATCHER_L1_ETH_RPC: http://l1-geth:${L1_HTTP_PORT}
      OP_BATCHER_L2_ETH_RPC: http://op-geth-sequencer:${OP_HTTP_PORT}
      OP_BATCHER_ROLLUP_RPC: http://op-node-sequencer:${ROLLUP_PORT}
      OP_BATCHER_ESPRESSO_URL: http://espresso-dev-node:${ESPRESSO_SEQUENCER_API_PORT},http://espresso-dev-node:${ESPRESSO_SEQUENCER_API_PORT}
    volumes:
      - ../packages/contracts-bedrock/lib/superchain-registry/ops/testdata/monorepo:/config
    command:
      - op-batcher
      - --espresso-light-client-addr=0x703848f4c85f18e3acd8196c8ec91eb0b7bd0797
      - --testing-espresso-batcher-private-key=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 # Default value for testing
      - --mnemonic=test test test test test test test test test test test junk # Arbitrary value for testing
      - --hd-path=m/44'/60'/0'/0/0 # Arbitrary value for testing
      - --throttle-threshold=0
      - --max-channel-duration=1
      - --target-num-frames=1

  # HTTP proxy for enclave Odyn proxy requirement
  http-proxy:
    image: alpine:latest
    command: >
      sh -c "
      apk add --no-cache tinyproxy &&
      echo 'Allow 127.0.0.1' >> /etc/tinyproxy/tinyproxy.conf &&
      echo 'Allow 0.0.0.0/0' >> /etc/tinyproxy/tinyproxy.conf &&
      echo 'DisableViaHeader Yes' >> /etc/tinyproxy/tinyproxy.conf &&
      tinyproxy -d
      "
    ports:
      - "3128:8888"
    networks:
      default:
        aliases:
          - proxy

  op-batcher-tee:
    profiles: ["tee"]
    build:
      context: ../
      dockerfile: espresso/docker/op-stack/Dockerfile
      target: op-batcher-enclave-target
    image: op-batcher-tee:espresso
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/enclave-tools.pid && kill -0 $(cat /tmp/enclave-tools.pid) 2>/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      l1-geth:
        condition: service_healthy
      op-geth-sequencer:
        condition: service_started
      op-node-sequencer:
        condition: service_started
      espresso-dev-node:
        condition: service_started
      l2-genesis:
        condition: service_completed_successfully
      http-proxy:
        condition: service_started
    network_mode: "host"
    environment:
      http_proxy: http://127.0.0.1:3128
      HTTP_PROXY: http://127.0.0.1:3128
      OPERATOR_PRIVATE_KEY: ${OPERATOR_PRIVATE_KEY}
      ENCLAVE_DEBUG: ${ENCLAVE_DEBUG:-false}
      CONTAINER_MONITOR_INTERVAL: ${CONTAINER_MONITOR_INTERVAL:-1}
      ENCLAVE_MEMORY_MB: ${ENCLAVE_MEMORY_MB:-4096}
      ENCLAVE_CPU_COUNT: ${ENCLAVE_CPU_COUNT:-2}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/source:ro
      - ./scripts/batcher-enclave-tool-image.sh:/app/espresso/scripts/batcher-enclave-tool-image.sh:ro
      - /tmp:/tmp
    privileged: true
    devices:
      - /dev/nitro_enclaves:/dev/nitro_enclaves
    restart: "no"
    command:
    - sh
    - -c
    - |
      export DEPLOYMENT_MODE=local
      export L1_RPC_URL="http://127.0.0.1:${L1_HTTP_PORT}"
      export L2_RPC_URL="http://127.0.0.1:${OP_HTTP_PORT}"
      export ROLLUP_RPC_URL="http://127.0.0.1:${ROLLUP_PORT}"
      export ESPRESSO_URL1="http://127.0.0.1:${ESPRESSO_SEQUENCER_API_PORT}"
      /source/espresso/docker/op-batcher-tee/run-enclave.sh 


  op-proposer:
    profiles: ["default"]
    build:
      context: ../
      dockerfile: espresso/docker/op-stack/Dockerfile
      target: op-proposer-target
    image: op-proposer:espresso
    depends_on:
      l2-rollup:
        condition: service_completed_successfully
      op-node-sequencer:
        condition: service_started
      op-batcher:
        condition: service_started
    environment:
      OP_PROPOSER_L1_ETH_RPC: http://l1-geth:${L1_HTTP_PORT}
      OP_PROPOSER_ROLLUP_RPC: http://op-node-sequencer:${ROLLUP_PORT}
    volumes:
      - ../packages/contracts-bedrock/lib/superchain-registry/ops/testdata/monorepo:/config
      - ./deployment/deployer:/deployer
    command:
      - sh
      - -c
      - |
        GAME_FACTORY=$(jq -r '.opChainDeployments[0].disputeGameFactoryProxyAddress' ./deployer/state.json)
        op-proposer \
          --proposal-interval 6s \
          --mnemonic "test test test test test test test test test test test junk" \
          --hd-path "m/44'/60'/0'/0/0" \
          --game-type 1 \
          --game-factory-address $$GAME_FACTORY

  espresso-dev-node:
    image: ghcr.io/espressosystems/espresso-sequencer/espresso-dev-node:release-colorful-snake
    depends_on:
      l1-geth:
        condition: service_healthy
    ports:
      - "${ESPRESSO_SEQUENCER_API_PORT}:${ESPRESSO_SEQUENCER_API_PORT}"
      - "${ESPRESSO_DEV_NODE_PORT}:${ESPRESSO_DEV_NODE_PORT}"
      - "${ESPRESSO_BUILDER_PORT}:${ESPRESSO_BUILDER_PORT}"
    volumes:
      - espresso-data:/data
    env_file:
      - ./.env
    environment:
      RUST_LOG: info
      ESPRESSO_DEV_NODE_L1_DEPLOYMENT: skip
      RUST_BACKTRACE: 1
      ESPRESSO_SEQUENCER_STORAGE_PATH: /data/espresso
      ESPRESSO_SEQUENCER_L1_PROVIDER: http://l1-geth:${L1_HTTP_PORT}
      ESPRESSO_DEPLOYER_ACCOUNT_INDEX: 0
      ESPRESSO_DEV_NODE_EPOCH_HEIGHT: '4294967295'
      ESPRESSO_SEQUENCER_ETH_MNEMONIC: "giant issue aisle success illegal bike spike question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy very lucky have athlete"

volumes:
  l1-data:
  op-data-seq:
  op-data-verifier:
  op-data-caff-node:
  espresso-data:
