@startuml

package "External Dependencies" {
  [ Kona ] as KonaExternal
  [OP Succinct] as OPSuccinctExternal
}

package "Celo" {
  [Kona] as KonaCelo
  [Celo Kona] as CeloKonaCelo
  [OP Succinct] as OPSuccinctCelo
}

package "Espresso" {
  [Kona] as KonaEspresso
  [Celo Kona] as CeloKonaEspresso
  [OP Succinct] as OPSuccinctEspresso
  [OP Integration] as OpIntegration
}




KonaCelo --> CeloKonaCelo: imports
CeloKonaCelo--> OPSuccinctCelo : imports
KonaExternal--> OPSuccinctExternal : imports
KonaCelo --> OPSuccinctCelo: imports

OPSuccinctExternal --> OPSuccinctCelo: fork
CeloKonaCelo --> CeloKonaEspresso: fork
OPSuccinctCelo --> OPSuccinctEspresso: fork
KonaExternal --> KonaCelo: fork
KonaCelo --> KonaEspresso: fork

OPSuccinctEspresso --> OpIntegration : imports docker images
KonaEspresso   --> CeloKonaEspresso: imports
CeloKonaEspresso  --> OPSuccinctEspresso : imports
KonaEspresso --> OPSuccinctEspresso : imports


@enduml
