name: Run Espresso Devnet tests
on:
  pull_request:
  push:
    branches:
      - "celo-integration*"
  workflow_dispatch:

jobs:
  devnet-test:
    runs-on: ubuntu-24.04-8core
    strategy:
      fail-fast: false
      matrix:
        group: [0, 1, 2, 3]
        include:
          - group: 0
            tests: "TestChallengeGame|TestChangeBatchInboxOwner"
            tee: false
          - group: 1
            tests: "TestSmokeWithoutTEE|TestBatcherRestart"
            tee: false
          - group: 2
            tests: "TestWithdrawal|TestBatcherSwitching"
            tee: false
          - group: 3
            tests: "TestSmokeWithTEE|TestForcedTransaction"
            tee: true
    env:
      ESPRESSO_DEVNET_TESTS_LIVENESS_PERIOD: "1m"
      ESPRESSO_DEVNET_TESTS_OUTAGE_PERIOD: "1m"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - name: Restore Nix cache
        id: cache-nix-restore
        uses: nix-community/cache-nix-action/restore@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
      - name: Set up Nix environment
        uses: nicknovitski/nix-develop@v1

      - name: Cache Go modules
        uses: actions/setup-go@v5

      - name: Compile contracts
        run: just compile-contracts

      - name: Load environment variables
        run: |
          while IFS= read -r line; do
            # Skip comments and empty lines
            if [[ ! "$line" =~ ^#.* ]] && [[ -n "$line" ]]; then
              # Remove quotes from values
              line=$(echo "$line" | sed 's/"\(.*\)"/\1/')
              echo "$line" >> $GITHUB_ENV
            fi
          done < ./espresso/.env
        shell: bash

      - name: Build Devnet without TEE
        run: |
          cd op-deployer
          just
          export PATH=$PATH:$PWD/bin
          cd ../espresso
          ./scripts/prepare-allocs.sh
          docker compose build
          docker compose pull l1-validator espresso-dev-node l1-data-init

      - name: Build Devnet with TEE
        if: matrix.tee
        run: |
          cd espresso
          COMPOSE_PROFILES=tee docker compose build

      - name: Run tests for group ${{ matrix.group }}
        run: go test -timeout 30m -p 1 -count 1 -run '${{ matrix.tests }}' -v ./espresso/devnet-tests/...

      - name: Save Nix cache
        uses: nix-community/cache-nix-action/save@v6
        if: always() && steps.cache-nix-restore.outputs.hit-primary-key != 'true'
        with:
          primary-key: ${{ steps.cache-nix-restore.outputs.primary-key }}
