name: Unit Tests

on:
  push:
    branches:
      - "celo-integration*"
  pull_request:
  workflow_dispatch:

jobs:
  espresso-unit-tests:
    name: espresso unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Run espresso package tests
        run: go test -v -count=1 -timeout 5m ./espresso/...

      - name: Run batcher espresso tests
        run: go test -v -count=1 -timeout 5m -run "TestWaitForCaffeinationHeight|TestNextBlockRange" ./op-batcher/batcher/
